### ISSUE TITLE
Updates recommended to .net and plugins

### ISSUE THREAD

**Issue by alindzon** [Randmar/API-Adaptor-C-#1]
the following updates have been tested.

.net 8.0 - upgrade from 5.0
System.identitymodel.tokens.jwt to 7.6.1 latest
Newtonsoft.json to 13.0.3 latest
Identitymodel to 7.0.0 latest
Restsharp if updated to latest breaks it.  Version 110.2.0 does work and is much more current.

**Comment by GislainArmand** [comment]
Updated to latest
